In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("food_coded.xls")

In [3]:
df.drop(111, axis=0, inplace=True)

In [4]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day',
       'vitamins', 'waffle_calories', 'weight'],
      dtype='object')

In [5]:
pd.set_option('display.max_rows',None)

In [6]:
df.isnull().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      18
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         16
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                2
fav_cuisine                      1
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              2
mother_education                 3
mother_profession                1
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     25
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [7]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35',
       'Personal ', '2.6', '3.67', '3.73', '3.79 bitch', '2.71', '3.68',
       '3.75', '3.92', 'Unknown', '3.77', '3.63', '3.882'], dtype=object)

In [8]:
# Convert to numeric 
df['GPA'] = pd.to_numeric(df['GPA'], errors='coerce')

In [9]:
df.dtypes

GPA                             float64
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                     object
comfort_food_reasons             object
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                     object
diet_current_coded                int64
drink                           float64
eating_changes                   object
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                object
fav_cuisine                      object
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                   object
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                     object
ideal_diet                       object
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend              object
mother_education                float64
mother_profession                object
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                      object
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                           object
dtype: object

In [10]:
# Find row where 'product' == 'apple' and change its 'price' column
row_index = df.loc[df['GPA'] == '3.79 bitch'].index   # first match
df.loc[row_index, 'price'] = 3.79

In [11]:
df['GPA'].unique()

array([2.4  , 3.654, 3.3  , 3.2  , 3.5  , 2.25 , 3.8  , 3.904, 3.4  ,
       3.6  , 3.1  ,   nan, 4.   , 2.2  , 3.87 , 3.7  , 3.9  , 2.8  ,
       3.   , 3.65 , 3.89 , 2.9  , 3.605, 3.83 , 3.292, 3.35 , 2.6  ,
       3.67 , 3.73 , 2.71 , 3.68 , 3.75 , 3.92 , 3.77 , 3.63 , 3.882])

In [12]:
mean_GPA = df['GPA'].mean() 
df['GPA'] =  df['GPA'].fillna(mean_GPA)

In [13]:
df['GPA'].unique()

array([2.4       , 3.654     , 3.3       , 3.2       , 3.5       ,
       2.25      , 3.8       , 3.904     , 3.4       , 3.6       ,
       3.1       , 3.41989076, 4.        , 2.2       , 3.87      ,
       3.7       , 3.9       , 2.8       , 3.        , 3.65      ,
       3.89      , 2.9       , 3.605     , 3.83      , 3.292     ,
       3.35      , 2.6       , 3.67      , 3.73      , 2.71      ,
       3.68      , 3.75      , 3.92      , 3.77      , 3.63      ,
       3.882     ])

In [14]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [15]:
mean_cal = df['calories_day'].mean() 
df['calories_day'] =  df['calories_day'].fillna(mean_cal)

In [16]:
df['calories_day'].unique()

array([3.03809524, 3.        , 4.        , 2.        ])

In [17]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    1
coffee                            0
comfort_food                      1
comfort_food_reasons              2
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                          16
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                          2
food_childhood                    1
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      1
ideal_diet                        1
ideal_diet_coded                  0
income                            1
indian_food                       0
italian_food                      0
life_rewarding                    1
marital_status                    1
meals_dinner_friend               2
mother_education                  3
mother_profession                 1
nutritional_check                 0
on_off_campus                     1
parents_cook                      0
pay_meal_out                      0
persian_food                      1
self_perception_weight            1
soup                              1
sports                            2
thai_food                         0
tortilla_calories                 1
turkey_calories                   0
type_sports                      25
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            2
price                           124
dtype: int64

In [18]:
df.shape

(124, 62)

In [19]:
df['calories_scone'].unique()

array([315., 420., 980.,  nan])

In [20]:
mean_cal = df['calories_scone'].mean() 
df['calories_scone'] =  df['calories_scone'].fillna(mean_cal)

In [21]:
df['calories_scone'].unique()

array([315.        , 420.        , 980.        , 501.38211382])

In [22]:
df['coffee'].unique()

array([1, 2])

In [23]:
df['comfort_food'].value_counts()

comfort_food
none                                                                                                 1
Mac and cheese, lasagna, Chinese food                                                                1
Macaroni and cheese, chicken noodle soup, pizza                                                      1
chips, ice cream, fruit snacks                                                                       1
carrots, plantain chips, almonds, popcorn                                                            1
Little Debbie snacks, donuts, pizza                                                                  1
pizza, pasta, mac and cheese                                                                         1
Chinese food, moes, sponge candy, homemade lasagne                                                   1
Ice cream, pizza, cookies                                                                            1
Pasta dishes, Cheesecake, Pancakes                                                                   1
Mashed potatoes, pasta                                                                               1
pizza, ice cream, cookies                                                                            1
cake, French fries, chicken nuggets                                                                  1
Cookies, burgers, chicken noodle soup, ice cream                                                     1
Chips sweets popcorn                                                                                 1
chocolate, fruit, and ice cream                                                                      1
Pizza cookies steak                                                                                  1
chocolate, pizza, and mashed potatoes                                                                1
mac and cheese, potato soup, ice cream, chips and cheese                                             1
Chips, ice cream                                                                                     1
pizza, pretzels, fruit snacks, deli sandwhich                                                        1
Chocolate, ice cream, cookie dough                                                                   1
Broccoli, spaghetti squash, quinoa, and grilled chicken                                              1
Pizza, burritos, slim jims                                                                           1
Chips, Mac and cheese, pizza, French fries                                                           1
Ice cream, cake, mozzarella sticks, pierogies                                                        1
Chocolate, Popcorn, Icecream                                                                         1
mac and cheese                                                                                       1
cookies, nutella, ice cream, coffee, fruit                                                           1
Chocolate, Chips, Ice cream, French Fires, Pizza                                                     1
candy, Chinese, mcdonalds                                                                            1
ice cream, cookies, ice cream                                                                        1
Doritos, mac and cheese, ice cream                                                                   1
Mac n Cheese, Lasagna, Pizza                                                                         1
rice, potato, seaweed soup                                                                           1
Pizza / Wings / Cheesecake                                                                           1
wine. mac and cheese, pizza, ice cream                                                               1
chips, rice, chicken curry,                                                                          1
Chinese, chips, cake                                                                                 1
Noodle ( any kinds of noodle), Tuna sandwich, and Egg.\r                                             1
Ice cream, chocolate, pizza, cucumber                                                                1
chocolate bar, ice cream, pretzels, potato chips and protein bars.                                   1
Burgers, indian and korean food\r                                                                    1
ice cream, pizza, Chinese food                                                                       1
Chocolate, Ice cream, pizza                                                                          1
Ice-cream, pizza, chocolate                                                                          1
Mac in cheese, pizza, mozzarella sticks                                                              1
Candy, salty snacks, toast                                                                           1
Chocolate, Pasta, Cookies                                                                            1
Pizza, soda, chocolate brownie, chicken tikka masala and butter naan                                 1
ice cream, chips, candy                                                                              1
Chips, chocolate, ,mozzarella sticks                                                                 1
dark chocolate, terra chips, reese's cups(dark chocolate), and bread/crackers with cottage cheese    1
Pizza, mashed potatoes, spaghetti                                                                    1
macaroni and cheese, stuffed peppers, hamburgers, french fries                                       1
watermelon, grapes, ice cream                                                                        1
mac & cheese, frosted brownies, chicken nuggs                                                        1
Soup, pasta, cake                                                                                    1
Mac and Cheese, Pizza, Ice Cream and French Fries                                                    1
Ice cream, cake, pop, pizza, and milkshakes.                                                         1
carrots and ranch, pretzels, dark chocolate                                                          1
Macaroons, truffles, peanut butter n chocolate ice cream                                             1
chocolate, chips, ice cream                                                                          1
cookies, mac-n-cheese, brownies, french fries,                                                       1
cookies, hot chocolate, beef jerky                                                                   1
Chicken fingers, pizza                                                                               1
Chips, ice cream, microwaveable foods                                                                1
chocolate, ice cream/milkshake, cookies                                                              1
Soup, pasta, brownies, cake                                                                          1
Chilli, soup, pot pie                                                                                1
burgers, chips, cookies                                                                              1
chocolate, sweets, ice cream                                                                         1
Fast food, pizza, subs                                                                               1
pizza, wings, Chinese                                                                                1
Chocolate, ice crea                                                                                  1
chips, cookies, ice cream                                                                            1
Saltfish, Candy and Kit Kat                                                                          1
cookies, donuts, candy bars                                                                          1
Pizza, fruit, spaghetti, chicken and Potatoes                                                        1
ice cream, cake, chocolate                                                                           1
Cookies, popcorn, and chips                                                                          1
chocolate, pasta, soup, chips, popcorn                                                               1
Pasta, grandma homemade chocolate cake anything homemade                                             1
Mac and cheese, chocolate, and pasta                                                                 1
Donuts, ice cream, chips                                                                             1
Ice cream, cheeseburgers, chips.                                                                     1
Chocolate, ice cream, french fries, pretzels                                                         1
Candy, brownies and soda.                                                                            1
Ice cream, chocolate, chips                                                                          1
Pizza, Mac and cheese, ice cream                                                                     1
frozen yogurt, pizza, fast food                                                                      1
Tomato soup, pizza, Fritos, Meatball sub, Dr. Pepper                                                 1
chips and dip, pepsi,                                                                                1
peanut butter, dessets, pretzels.                                                                    1
Grandma's Chinese, Peruvian food from back home, and sushi                                           1
Mac n Cheese. Chips and salsa. Ice cream.                                                            1
Chocolate, ice cream, pasta                                                                          1
Pizza chocolate chips bagels ice Capps                                                               1
Pizza, Ice Cream, Chicken Wings                                                                      1
chips, dip, fries, pizza                                                                             1
peanut butter sandwich, pretzals, garlic bread                                                       1
fries, chips, fried chicken, pizza, grapes                                                           1
Pizza, chocolate, and ice cream                                                                      1
Burger                                                                                               1
Popcorn, Chex Mix, Pizza                                                                             1
fried chicken. mashed potatoes, mac and cheese                                                       1
pizza, ice cream, chips                                                                              1
Chex-mix, Wegmans cookies, Cheez-Its                                                                 1
popcorn, chips, candy, & fries                                                                       1
Mac and cheese, fried chicken, cornbread                                                             1
Potato chips, ice cream, chocolate, cookies                                                          1
ice cream, cereal, and salt and vinegar chips                                                        1
ice cream, cookie dough, cookies, cheese                                                             1
Ice cream, chocolate, twizzlers                                                                      1
Pizza, Ice cream, fries, cereal, cookies                                                             1
Candy\rPop\rChocolate \rChipotle \rMoe's                                                             1
chocolate, popcorn, ice cream                                                                        1
chocolate, chips, candy                                                                              1
pizza, doughnuts, mcdonalds                                                                          1
mac n cheese, peanut butter and banana sandwich, omelet                                              1
french fries, chips, ice cream                                                                       1
Ice cream, cookies,  Chinese food, and chicken nuggets                                               1
Chocolates, pizza, and Ritz.                                                                         1
Name: count, dtype: int64

In [24]:
mean_cal = df['comfort_food'].mode() 
df['comfort_food'] =  df['comfort_food'].fillna(mean_cal)

In [25]:
df.dtypes

GPA                             float64
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                     object
comfort_food_reasons             object
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                     object
diet_current_coded                int64
drink                           float64
eating_changes                   object
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                object
fav_cuisine                      object
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                   object
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                     object
ideal_diet                       object
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend              object
mother_education                float64
mother_profession                object
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                      object
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                           object
price                           float64
dtype: object

In [26]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                          16
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                          2
food_childhood                    1
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      1
ideal_diet                        1
ideal_diet_coded                  0
income                            1
indian_food                       0
italian_food                      0
life_rewarding                    1
marital_status                    1
meals_dinner_friend               2
mother_education                  3
mother_profession                 1
nutritional_check                 0
on_off_campus                     1
parents_cook                      0
pay_meal_out                      0
persian_food                      1
self_perception_weight            1
soup                              1
sports                            2
thai_food                         0
tortilla_calories                 1
turkey_calories                   0
type_sports                      25
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            2
price                           124
dtype: int64

In [27]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drunkeness',
       'stress, boredom, cold weather', 'stres, boredom, and nighttime',
       'Hunger and Boredom ',
       'boredom, sadness, and if it has a good taste. ',
       'boredom, stressed, sad', 'Boredom usually', 'Stress',
       'boredom, stress', 'No reasons ',
       "Usually if I'm sad or depressed. ", 'Tired ', 'Boredom!, sadness',
       'All of the above; sadness, boredom and confusion ',
       'Stress, boredom, craving', 'Hunger, boredom',
       'sadness, boredom, & anger ', 'Boredom, happiness, distraught ',
       'stressed, upset, or just craving a cheat meal',
       'They taste better than other food. They are a pickme up. They are easy to make',
       'Stress, boredom', 'Lazy', 'Boredom, sadness and anger ',
       'Boredom, sadness', 'stress, anger and boredom', 'bored, stress',
       'I usually only eat comfort foods when I am bored. I will also eat them when I am happy to celebrate and then when I am sad to comfort me.',
       'Just cause ', 'Stress, boredom, sadness',
       'Boredom. Celebration. ', 'Sadness, boredom, lonely.',
       'I do not really eat "comfort food" but I guess sadness, special occasions, and anxiety ',
       'boredom, sadness', 'sadness', 'Bordem, happiness, sadness',
       'Stress, sadness, bored ', 'Boredom, stress, and it tastes good',
       'Bad day, bored, sadness',
       'Boredom, being in your period, and long bus rides for softball',
       'boredom, anger, happy', 'Boredom, stress', nan,
       'sadness, stressed, boredom', 'boredom and stress',
       'Boredom comfort hunger ', 'happiness, hunger, sadness',
       'Boredom, sadness, or with friends ',
       'Sadness, Loneliness, Boredom', 'Mostly Stress',
       'boredom, sadness ', 'when i am sad or craving',
       'stress, boredom, college as whole ', 'Boredom and stress',
       'Stress, sadness, boredom', 'laziness and hungover',
       'Boredom, hunger, snacking.', 'Happiness, sadness, celebration.',
       'Boredom, anger and just being hungry in general.',
       'Depression, comfort, accessibility ',
       'they are yummy, my boyfriend sometimes makes me sad, boredom',
       'Sad, bored, excited', 'boredom, stress, mood swings',
       'Anger, sadness',
       'Anxiousness, watching TV I desire "comfort food" ',
       'Boredom, sadness, anxiety', 'Boredom, laziness, anger',
       'Stress and sadness',
       'I am always stressed out, and bored when I am in my apartment. ',
       'Stress, frustration, self-consciousness ', 'Sadness and cravings',
       'Sadness, happiness and boredom', 'Boredom and sadness',
       'sadness, happiness and hunger',
       'Stress, boredom and physical activity',
       'loneliness, homework, boredom ',
       "When i'm  eating with my close friends/ Food smell or look good/ when I feel tired",
       'Happiness, boredom, social event', 'boredom and sadness ',
       'Loneliness / Homesick / Sadness',
       'happiness, they are some of my favorite foods',
       'hormones, Premenstrual syndrome.'], dtype=object)

In [28]:
df['cuisine'].unique()

array([nan,  1.,  3.,  2.,  6.,  4.,  5.])

In [29]:
mean_cu = df['cuisine'].mean() 
df['cuisine'] =  df['cuisine'].fillna(mean_cu)

In [30]:
df['cuisine'].unique()

array([1.38888889, 1.        , 3.        , 2.        , 6.        ,
       4.        , 5.        ])

In [31]:
df['exercise'].unique()

array([ 1.,  2.,  3., nan])

In [32]:
df[df['exercise']==' '].index.tolist()

[]

In [33]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                          2
food_childhood                    1
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      1
ideal_diet                        1
ideal_diet_coded                  0
income                            1
indian_food                       0
italian_food                      0
life_rewarding                    1
marital_status                    1
meals_dinner_friend               2
mother_education                  3
mother_profession                 1
nutritional_check                 0
on_off_campus                     1
parents_cook                      0
pay_meal_out                      0
persian_food                      1
self_perception_weight            1
soup                              1
sports                            2
thai_food                         0
tortilla_calories                 1
turkey_calories                   0
type_sports                      25
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            2
price                           124
dtype: int64

In [34]:
numeric_columns =  df.select_dtypes(include=['number']).columns

In [35]:
df[numeric_columns].isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current_coded                0
drink                             2
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
fav_cuisine_coded                 0
fav_food                          2
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
ideal_diet_coded                  0
income                            1
indian_food                       0
italian_food                      0
life_rewarding                    1
marital_status                    1
mother_education                  3
nutritional_check                 0
on_off_campus                     1
parents_cook                      0
pay_meal_out                      0
persian_food                      1
self_perception_weight            1
soup                              1
sports                            2
thai_food                         0
tortilla_calories                 1
turkey_calories                   0
veggies_day                       0
vitamins                          0
waffle_calories                   0
price                           124
dtype: int64

In [36]:
for column in numeric_columns:
 df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

In [37]:
ob_columns = df.select_dtypes(include=['object']).columns

In [38]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     2
diet_current             1
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             1
ideal_diet               1
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [39]:
for column in numeric_columns:
 df[ob_columns] = df[ob_columns].fillna(df[ob_columns].mode())

In [40]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     2
diet_current             0
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             0
ideal_diet               0
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [41]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400,2,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,1.0,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654,1,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300,1,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200,1,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240",NaN
4,3.500,1,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,4,940.0,500,Softball,4,2,760,190,NaN

In [42]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drunkeness',
       'stress, boredom, cold weather', 'stres, boredom, and nighttime',
       'Hunger and Boredom ',
       'boredom, sadness, and if it has a good taste. ',
       'boredom, stressed, sad', 'Boredom usually', 'Stress',
       'boredom, stress', 'No reasons ',
       "Usually if I'm sad or depressed. ", 'Tired ', 'Boredom!, sadness',
       'All of the above; sadness, boredom and confusion ',
       'Stress, boredom, craving', 'Hunger, boredom',
       'sadness, boredom, & anger ', 'Boredom, happiness, distraught ',
       'stressed, upset, or just craving a cheat meal',
       'They taste better than other food. They are a pickme up. They are easy to make',
       'Stress, boredom', 'Lazy', 'Boredom, sadness and anger ',
       'Boredom, sadness', 'stress, anger and boredom', 'bored, stress',
       'I usually only eat comfort foods when I am bored. I will also eat them when I am happy to celebrate and then when I am sad to comfort me.',
       'Just cause ', 'Stress, boredom, sadness',
       'Boredom. Celebration. ', 'Sadness, boredom, lonely.',
       'I do not really eat "comfort food" but I guess sadness, special occasions, and anxiety ',
       'boredom, sadness', 'sadness', 'Bordem, happiness, sadness',
       'Stress, sadness, bored ', 'Boredom, stress, and it tastes good',
       'Bad day, bored, sadness',
       'Boredom, being in your period, and long bus rides for softball',
       'boredom, anger, happy', 'Boredom, stress', nan,
       'sadness, stressed, boredom', 'boredom and stress',
       'Boredom comfort hunger ', 'happiness, hunger, sadness',
       'Boredom, sadness, or with friends ',
       'Sadness, Loneliness, Boredom', 'Mostly Stress',
       'boredom, sadness ', 'when i am sad or craving',
       'stress, boredom, college as whole ', 'Boredom and stress',
       'Stress, sadness, boredom', 'laziness and hungover',
       'Boredom, hunger, snacking.', 'Happiness, sadness, celebration.',
       'Boredom, anger and just being hungry in general.',
       'Depression, comfort, accessibility ',
       'they are yummy, my boyfriend sometimes makes me sad, boredom',
       'Sad, bored, excited', 'boredom, stress, mood swings',
       'Anger, sadness',
       'Anxiousness, watching TV I desire "comfort food" ',
       'Boredom, sadness, anxiety', 'Boredom, laziness, anger',
       'Stress and sadness',
       'I am always stressed out, and bored when I am in my apartment. ',
       'Stress, frustration, self-consciousness ', 'Sadness and cravings',
       'Sadness, happiness and boredom', 'Boredom and sadness',
       'sadness, happiness and hunger',
       'Stress, boredom and physical activity',
       'loneliness, homework, boredom ',
       "When i'm  eating with my close friends/ Food smell or look good/ when I feel tired",
       'Happiness, boredom, social event', 'boredom and sadness ',
       'Loneliness / Homesick / Sadness',
       'happiness, they are some of my favorite foods',
       'hormones, Premenstrual syndrome.'], dtype=object)

In [43]:
df['exercise'].unique()

array([1.        , 2.        , 3.        , 1.58558559])

In [44]:
mean_ex = df['exercise'].mode() 
df['exercise'] =  df['exercise'].fillna(mean_ex)

In [45]:
df['exercise'].unique()

array([1.        , 2.        , 3.        , 1.58558559])

In [46]:
df['cook'].unique()

array([2.        , 3.        , 1.        , 5.        , 4.        ,
       2.79338843])

In [47]:
mean_cook = df['cook'].mean() 
df['cook'] =  df['cook'].fillna(mean_cook)

In [48]:
df['cook'].unique()

array([2.        , 3.        , 1.        , 5.        , 4.        ,
       2.79338843])

In [49]:
df['comfort_food_reasons_coded'].unique()

array([9.        , 1.        , 2.        , 4.        , 3.        ,
       7.        , 6.        , 5.        , 8.        , 2.69811321])

In [50]:
mean_reason = df['comfort_food_reasons_coded'].mean() 
df['comfort_food_reasons_coded'] =  df['comfort_food_reasons_coded'].fillna(mean_reason)

In [51]:
df['comfort_food_reasons_coded'].unique()

array([9.        , 1.        , 2.        , 4.        , 3.        ,
       7.        , 6.        , 5.        , 8.        , 2.69811321])

In [52]:
df['father_education'].unique()

array([5.        , 2.        , 4.        , 1.        , 3.        ,
       3.49593496])

In [53]:
mean_fe = df['father_education'].mean() 
df['father_education'] =  df['father_education'].fillna(mean_fe)

In [54]:
df['father_education'].unique()

array([5.        , 2.        , 4.        , 1.        , 3.        ,
       3.49593496])

In [55]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded        0
cook                              0
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      0
diet_current_coded                0
drink                             0
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        0
ethnic_food                       0
exercise                          0
father_education                  0
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                          0
food_childhood                    1
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      0
ideal_diet                        0
ideal_diet_coded                  0
income                            0
indian_food                       0
italian_food                      0
life_rewarding                    0
marital_status                    0
meals_dinner_friend               2
mother_education                  0
mother_profession                 1
nutritional_check                 0
on_off_campus                     0
parents_cook                      0
pay_meal_out                      0
persian_food                      0
self_perception_weight            0
soup                              0
sports                            0
thai_food                         0
tortilla_calories                 0
turkey_calories                   0
type_sports                      25
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            2
price                           124
dtype: int64

In [56]:
df['drink'].unique()

array([1.        , 2.        , 1.55737705])

In [57]:
mean_fe = df['drink'].mean() 
df['drink'] =  df['drink'].fillna(mean_fe)

In [58]:
df['drink'].unique()

array([1.        , 2.        , 1.55737705])

In [59]:
df['diet_current'].unique()

array(['eat good and exercise',
       "I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ",
       'toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner',
       'College diet, cheap and easy foods most nights. Weekends traditionally, cook better homemade meals  ',
       'I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ',
       "My current diet is terrible. I barely have time to eat a meal in a day. When i do eat it's mostly not healthy.",
       'I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.',
       'I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.',
       'I eat whatever I want in moderation.',
       "I eat healthy all the time when possible. I treat myself occasionally. I don't really like the greasy meals, if anything I would eat sweets over the greasy meals.  ",
       'i eat very healthy. Maybe eat out 1-2 times a week.',
       'I am very health concious. I eat many fruits, veggies, and protiens. ',
       'I focus mostly on proteins and fruits. I eat a lot less vegetables and a few carbohydrates.',
       'Not as healthy when I am at school compared to home. Still very aware of the nutrition I am taking in.',
       'Making sure I have enough protein intake, as well with fibre, vitamins and carbs. ',
       'I like a lot of foods that arent home cooked or healthy for you.',
       'I eat very healthy ',
       'My current diet is eggs and a meat every morning for breakfast. For lunch ill usually have some pasta or rice with a meat and sometimes a side of veggies. for dinner i usually eat less carbs and more protein and veggies. ',
       'I eat lots of fruit and veggies. I eat lots of chicken.',
       "Current diet right now isn't very good. I eat at the school's cafeteria and they do not have the best choices.",
       'I eat 2 meals a day, lunch and dinner',
       'Random. Not strict diet, changes during season', 'balanced ',
       '2 meals a day. Rarely eat snacks. Fairly balanced diet. ',
       'I eat a lot of chicken and try to cook my own meals as much as possible using a lot of rice and vegetables.',
       'vegetarian, eat breakfast some days before class, can eat a lot of junk food so I refrain from allowing myself to buy any',
       "Most healthy diet, but since I'm an athlete have room for some bad foods to burn off quickly ",
       'Very healthy. Good balance of proteins and vegetables ',
       'Whats necessary for survival.  ', 'anything and everything',
       'I eat some vegetables almost everyday and fruit a couple of times a week. I eat meat a few times a week. I dont eat fast food and try to limit fried food.',
       'Diet consists of 3000-4000 calories a day well rounded from meats, vegetables, and fruit.',
       'Not that balanced, but I try not to eat fatty or fried foods.',
       'I eat a a lot of carbs from pizza and pasta. I also eat a lot of cookies. ',
       'egan dining',
       'A lot of rice and veggies, eggs for breakfast, chicken is usually the only kind of meat I eat.',
       "I eat out more often then not. I try to make sure when I eat out it isn't fast food, but instead something healthy like Panera. ",
       'I do not get to eat as well as I did.  I wish I ate better, but in college it is hard because of money.',
       'I eat three meals per day usually. I eat a lot of sandwiches and fruit.',
       'Unhealthy foods from the cafe ',
       'I will eat a full bleakest every morning consisting of eggs, potatoes, and a type of meat with juice. I will have a sandwich or something light for lunch. For dinner I will have meat and vegetables of some sort.  ',
       'I eat food ',
       'Light breakfast, yogurt or grandola bar. No luch but (healthy) snacks throughout this time period until dinner. Full dinner with meat, vegetables and fruit.',
       'It needs some re-structuring. Mostly, I eat well but I would like to improve on my water, fruit and veggie consumption. ',
       'I am on a very balanced diet, eating 4-5 small meals a day filled with fruits, vegetables, lean meat, and good carbs. ',
       'Healthy, includes many fruits and vegetables. Probably too many carbs. ',
       'At school I eat a lot of pizza or burgers with fries. Occasionally I try to have a salad or a fruit juice with this. I also try to eat more of a home cooked meal with vegetables.',
       'lots of pasta and carbs along with lean meats. Also at time some soda and junk food',
       "My current diet consists of cafeteria food, which isn't necessarily ideal. I try to eat as healthy as possible but I find myself turning to unhealthy food more often than healthy.",
       'I eat alot carbs. Protein (meat) is beautiful.',
       'Healthier than most but not 100% clean.', 'Great ',
       'My diet is mostly chicken rice and veggies. I mix in fruit between workouts and snacks like power bars and what not. ',
       '65 and out',
       'Very healthy and clean. A lot of protein and vegetables',
       'What ever the dinning hall is serving. When i am hungry i look for something filling more then healthy. ',
       'I usually eat very healthy. I incorporate fresh fruits and vegetables into every meal.',
       'I eat very heathy on a daily basis ',
       'For breakfast I have oatmeal. For lunch I have a sandwich and fruit. For dinner I usually have a piece of meat, rice or pasta, and a vegetable. ',
       'Simple breakfast of cereal or yogurt. Lunch is something like a deli meat sandwich. Dinner is a full meal. Veggies meat and starch. ',
       'My diet consists of fruits, vegetables, grains, dairy, and proteins.',
       'My diet is pretty healthy and consists of chicken, turcky, and veggies. I rarely eat unhealthy food or fast food.',
       'I try to eat as healthy as possible. 3 meals a day that are well-balanced.',
       'High in protein, fruits, and veggies. Low in fats.',
       'I eat fruit and vetagables with every meal. I only drink water, no soda. I tend to stay away from greasy food. ',
       "I don't follow a diet, I eat whatever I want",
       'My current diet usually includes at least one serving of vegetables per day, and I usually am eating fruits and whole grain things. ',
       'I typically try to eat healthy but being away at school makes it harder. I try to avoid junk food as well and trying to only eat it on the weekends.',
       'My current diet is balanced and includes food from all the food groups. ',
       'I am not vegetarian. I love red meat like steak and salami. I try to limit the amount of carbs I eat',
       'Healthy and light',
       'My meals consist of a vegetable, a meat and usually a carbohydrate. I eat a lot of fruit and snack in between meals on little things.',
       'I eat somewhat healthy. The food at egan is not the best.',
       'I have a diet of meats and other high protein foods. ',
       'It is pretty balanced with a diverse mixture of proteins, carbohydrates, vitamins and minerals. Fruits and chicken dominate my diet. ',
       'I normally eat a salad every day. I try to get at least every food group into my diet',
       'Current diet is rather poor.  I eat a lot of chicken and carbs.  I also tend to eat a lot of desserts.',
       'Meat carbs and candy ',
       'At school its hard but usually a granola bar and fruit for breakfast, a wrap for dinner or lunch, and then veggies and hummus.',
       'No diet. I eat what makes me feel good',
       'If there is berries I will eat them.  Eat any kind of pasta.  Hate cooked vegetables',
       'I eat fruits, dairy and carbs ',
       'I eat two-tree meals per day. Always eat a breakfast. ',
       'I eat healthy as well as unhealthy. I try to keep a balanced diet but often eat junk food with friends.',
       'I eat a paleo based diet high in protein and low in fat. I stay away from processed foods as much as I can.',
       "I try to eat something light for breakfast like cereal or an apple. For lunch I eat sandwiches or pasta also something somewhat light and I eat however much I'm hungry for at dinner. Sometimes I try to be healthy with a salad or something and then I get dessert ",
       'Eat fruits and vegetables daily and with almost every meal. Diet mostly consists of meat as well. ',
       'I try to eat healthy but sometimes drink soda pop and I enjoy desserts. harder to eat healthy when I am at school. ',
       'High protein and high carbs with fruits and vegetables as needed',
       'i currently eat a lot of salad, but do not eat 3 times a day nor eat breakfast ',
       "I used to eat whatever but since i've come to college i try to eat fruits and vegetables everyday. I also avoid fried foods.",
       "I eat very basic foods like pizza and pasta. I don't try many new things. ",
       'My diet consists of high levels of meats with some vegetables. Coexisting with varying levels of sugars ',
       'Very poor. Heavy carb consumption. ',
       'Complete diet. protein vegetables and carbs',
       'I eat usually 2 times a day, either breakfast and dinner or lunch and dinner.  I feel that is enough for me.',
       'Currently whatever Egan has at the moment.',
       'I try to maintain a healthy diet. I always try to eat foods that are beneficial to my health and that will impact me in the long run.',
       'Somewhat unhealthy. This is due to my hectic work and school schedule.',
       'i drink alot of lemon water, and milk. i also eat ice cream frequently after dinner. but i also eat lots of fruits and veggies',
       'I typically eat very healthy. i consume fruits and vegetables in about every meal. ',
       'At this time it is very touch and go. Some days I live on sandwiches and ice cream while other days I eat lots of fruits and vegetables. ',
       'A very healthy diet. Avoiding junk foods, and any white breads. ',
       'I have been eating mainly proteins and some fruits and vegetables every day with some less healthy snack foods.  ',
       'High in carbs, but I have recently tried to cut down on fats, salt, and sugars. I choose more organic options as well as more fruits and vegetables. ',
       'Since I am a college student I rarely cook full meals with protein, vegetables and starch. I usually just heat up leftovers from a restaurant or go eat casual food at the dining hall.',
       'I try to eat a balanced meal. I refrain from anything too fatty. ',
       'moderately health conscious ',
       'protein, carbs, less fruits and vegetables, some sweets ',
       'I eat at least 2 times a day at the universities dining places. I also sometimes cook myself and try to eat healthy a majority of the time. ',
       'I eat a lot of proteins and fruit and vegetables. I try to stay away from carbohydrates and sugary foods.',
       'My current diet would be considered a "college diet". I eat a lot of pizza and ramen noodles. ',
       'Not very healthy',
       'I currently eat an abundance of carbohydrates. I have a low intake of protein. I overly intake calcium.',
       'It is very unbalance. Mostly fat food, Lack of vegetables.',
       'I eat in dining hall of school everyday. I usually have both meat and a little vegetable in every meal. ',
       'Try to eat as healthy as possible. A few days where fast food comes into play because of classes. ',
       'My diet is mostly whatever I get to eat in the grotto commons. Sometimes, I eat outside',
       'My diet consists mainly of coffee, water, fruits, vegetables, and chicken. I tend to stay away from bread and pasta as much as possible. ',
       'A college student with an imbalanced diet trying to be healthy.',
       'Rice, oatmeal, and tea',
       'I try to eat as healthy as possible everyday.  I have fruit, yogurt and a protein shake everyday.  The other foods i eat vary on a day to day basis.',
       'high in protein and low in carbohydrates.'], dtype=object)

In [60]:
mean_dc = df['diet_current'].mode() 
df['diet_current'] =  df['diet_current'].fillna(mean_dc)

In [61]:
df['diet_current'].unique()

array(['eat good and exercise',
       "I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ",
       'toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner',
       'College diet, cheap and easy foods most nights. Weekends traditionally, cook better homemade meals  ',
       'I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ',
       "My current diet is terrible. I barely have time to eat a meal in a day. When i do eat it's mostly not healthy.",
       'I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.',
       'I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.',
       'I eat whatever I want in moderation.',
       "I eat healthy all the time when possible. I treat myself occasionally. I don't really like the greasy meals, if anything I would eat sweets over the greasy meals.  ",
       'i eat very healthy. Maybe eat out 1-2 times a week.',
       'I am very health concious. I eat many fruits, veggies, and protiens. ',
       'I focus mostly on proteins and fruits. I eat a lot less vegetables and a few carbohydrates.',
       'Not as healthy when I am at school compared to home. Still very aware of the nutrition I am taking in.',
       'Making sure I have enough protein intake, as well with fibre, vitamins and carbs. ',
       'I like a lot of foods that arent home cooked or healthy for you.',
       'I eat very healthy ',
       'My current diet is eggs and a meat every morning for breakfast. For lunch ill usually have some pasta or rice with a meat and sometimes a side of veggies. for dinner i usually eat less carbs and more protein and veggies. ',
       'I eat lots of fruit and veggies. I eat lots of chicken.',
       "Current diet right now isn't very good. I eat at the school's cafeteria and they do not have the best choices.",
       'I eat 2 meals a day, lunch and dinner',
       'Random. Not strict diet, changes during season', 'balanced ',
       '2 meals a day. Rarely eat snacks. Fairly balanced diet. ',
       'I eat a lot of chicken and try to cook my own meals as much as possible using a lot of rice and vegetables.',
       'vegetarian, eat breakfast some days before class, can eat a lot of junk food so I refrain from allowing myself to buy any',
       "Most healthy diet, but since I'm an athlete have room for some bad foods to burn off quickly ",
       'Very healthy. Good balance of proteins and vegetables ',
       'Whats necessary for survival.  ', 'anything and everything',
       'I eat some vegetables almost everyday and fruit a couple of times a week. I eat meat a few times a week. I dont eat fast food and try to limit fried food.',
       'Diet consists of 3000-4000 calories a day well rounded from meats, vegetables, and fruit.',
       'Not that balanced, but I try not to eat fatty or fried foods.',
       'I eat a a lot of carbs from pizza and pasta. I also eat a lot of cookies. ',
       'egan dining',
       'A lot of rice and veggies, eggs for breakfast, chicken is usually the only kind of meat I eat.',
       "I eat out more often then not. I try to make sure when I eat out it isn't fast food, but instead something healthy like Panera. ",
       'I do not get to eat as well as I did.  I wish I ate better, but in college it is hard because of money.',
       'I eat three meals per day usually. I eat a lot of sandwiches and fruit.',
       'Unhealthy foods from the cafe ',
       'I will eat a full bleakest every morning consisting of eggs, potatoes, and a type of meat with juice. I will have a sandwich or something light for lunch. For dinner I will have meat and vegetables of some sort.  ',
       'I eat food ',
       'Light breakfast, yogurt or grandola bar. No luch but (healthy) snacks throughout this time period until dinner. Full dinner with meat, vegetables and fruit.',
       'It needs some re-structuring. Mostly, I eat well but I would like to improve on my water, fruit and veggie consumption. ',
       'I am on a very balanced diet, eating 4-5 small meals a day filled with fruits, vegetables, lean meat, and good carbs. ',
       'Healthy, includes many fruits and vegetables. Probably too many carbs. ',
       'At school I eat a lot of pizza or burgers with fries. Occasionally I try to have a salad or a fruit juice with this. I also try to eat more of a home cooked meal with vegetables.',
       'lots of pasta and carbs along with lean meats. Also at time some soda and junk food',
       "My current diet consists of cafeteria food, which isn't necessarily ideal. I try to eat as healthy as possible but I find myself turning to unhealthy food more often than healthy.",
       'I eat alot carbs. Protein (meat) is beautiful.',
       'Healthier than most but not 100% clean.', 'Great ',
       'My diet is mostly chicken rice and veggies. I mix in fruit between workouts and snacks like power bars and what not. ',
       '65 and out',
       'Very healthy and clean. A lot of protein and vegetables',
       'What ever the dinning hall is serving. When i am hungry i look for something filling more then healthy. ',
       'I usually eat very healthy. I incorporate fresh fruits and vegetables into every meal.',
       'I eat very heathy on a daily basis ',
       'For breakfast I have oatmeal. For lunch I have a sandwich and fruit. For dinner I usually have a piece of meat, rice or pasta, and a vegetable. ',
       'Simple breakfast of cereal or yogurt. Lunch is something like a deli meat sandwich. Dinner is a full meal. Veggies meat and starch. ',
       'My diet consists of fruits, vegetables, grains, dairy, and proteins.',
       'My diet is pretty healthy and consists of chicken, turcky, and veggies. I rarely eat unhealthy food or fast food.',
       'I try to eat as healthy as possible. 3 meals a day that are well-balanced.',
       'High in protein, fruits, and veggies. Low in fats.',
       'I eat fruit and vetagables with every meal. I only drink water, no soda. I tend to stay away from greasy food. ',
       "I don't follow a diet, I eat whatever I want",
       'My current diet usually includes at least one serving of vegetables per day, and I usually am eating fruits and whole grain things. ',
       'I typically try to eat healthy but being away at school makes it harder. I try to avoid junk food as well and trying to only eat it on the weekends.',
       'My current diet is balanced and includes food from all the food groups. ',
       'I am not vegetarian. I love red meat like steak and salami. I try to limit the amount of carbs I eat',
       'Healthy and light',
       'My meals consist of a vegetable, a meat and usually a carbohydrate. I eat a lot of fruit and snack in between meals on little things.',
       'I eat somewhat healthy. The food at egan is not the best.',
       'I have a diet of meats and other high protein foods. ',
       'It is pretty balanced with a diverse mixture of proteins, carbohydrates, vitamins and minerals. Fruits and chicken dominate my diet. ',
       'I normally eat a salad every day. I try to get at least every food group into my diet',
       'Current diet is rather poor.  I eat a lot of chicken and carbs.  I also tend to eat a lot of desserts.',
       'Meat carbs and candy ',
       'At school its hard but usually a granola bar and fruit for breakfast, a wrap for dinner or lunch, and then veggies and hummus.',
       'No diet. I eat what makes me feel good',
       'If there is berries I will eat them.  Eat any kind of pasta.  Hate cooked vegetables',
       'I eat fruits, dairy and carbs ',
       'I eat two-tree meals per day. Always eat a breakfast. ',
       'I eat healthy as well as unhealthy. I try to keep a balanced diet but often eat junk food with friends.',
       'I eat a paleo based diet high in protein and low in fat. I stay away from processed foods as much as I can.',
       "I try to eat something light for breakfast like cereal or an apple. For lunch I eat sandwiches or pasta also something somewhat light and I eat however much I'm hungry for at dinner. Sometimes I try to be healthy with a salad or something and then I get dessert ",
       'Eat fruits and vegetables daily and with almost every meal. Diet mostly consists of meat as well. ',
       'I try to eat healthy but sometimes drink soda pop and I enjoy desserts. harder to eat healthy when I am at school. ',
       'High protein and high carbs with fruits and vegetables as needed',
       'i currently eat a lot of salad, but do not eat 3 times a day nor eat breakfast ',
       "I used to eat whatever but since i've come to college i try to eat fruits and vegetables everyday. I also avoid fried foods.",
       "I eat very basic foods like pizza and pasta. I don't try many new things. ",
       'My diet consists of high levels of meats with some vegetables. Coexisting with varying levels of sugars ',
       'Very poor. Heavy carb consumption. ',
       'Complete diet. protein vegetables and carbs',
       'I eat usually 2 times a day, either breakfast and dinner or lunch and dinner.  I feel that is enough for me.',
       'Currently whatever Egan has at the moment.',
       'I try to maintain a healthy diet. I always try to eat foods that are beneficial to my health and that will impact me in the long run.',
       'Somewhat unhealthy. This is due to my hectic work and school schedule.',
       'i drink alot of lemon water, and milk. i also eat ice cream frequently after dinner. but i also eat lots of fruits and veggies',
       'I typically eat very healthy. i consume fruits and vegetables in about every meal. ',
       'At this time it is very touch and go. Some days I live on sandwiches and ice cream while other days I eat lots of fruits and vegetables. ',
       'A very healthy diet. Avoiding junk foods, and any white breads. ',
       'I have been eating mainly proteins and some fruits and vegetables every day with some less healthy snack foods.  ',
       'High in carbs, but I have recently tried to cut down on fats, salt, and sugars. I choose more organic options as well as more fruits and vegetables. ',
       'Since I am a college student I rarely cook full meals with protein, vegetables and starch. I usually just heat up leftovers from a restaurant or go eat casual food at the dining hall.',
       'I try to eat a balanced meal. I refrain from anything too fatty. ',
       'moderately health conscious ',
       'protein, carbs, less fruits and vegetables, some sweets ',
       'I eat at least 2 times a day at the universities dining places. I also sometimes cook myself and try to eat healthy a majority of the time. ',
       'I eat a lot of proteins and fruit and vegetables. I try to stay away from carbohydrates and sugary foods.',
       'My current diet would be considered a "college diet". I eat a lot of pizza and ramen noodles. ',
       'Not very healthy',
       'I currently eat an abundance of carbohydrates. I have a low intake of protein. I overly intake calcium.',
       'It is very unbalance. Mostly fat food, Lack of vegetables.',
       'I eat in dining hall of school everyday. I usually have both meat and a little vegetable in every meal. ',
       'Try to eat as healthy as possible. A few days where fast food comes into play because of classes. ',
       'My diet is mostly whatever I get to eat in the grotto commons. Sometimes, I eat outside',
       'My diet consists mainly of coffee, water, fruits, vegetables, and chicken. I tend to stay away from bread and pasta as much as possible. ',
       'A college student with an imbalanced diet trying to be healthy.',
       'Rice, oatmeal, and tea',
       'I try to eat as healthy as possible everyday.  I have fruit, yogurt and a protein shake everyday.  The other foods i eat vary on a day to day basis.',
       'high in protein and low in carbohydrates.'], dtype=object)

In [62]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded        0
cook                              0
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      0
diet_current_coded                0
drink                             0
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        0
ethnic_food                       0
exercise                          0
father_education                  0
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                          0
food_childhood                    1
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      0
ideal_diet                        0
ideal_diet_coded                  0
income                            0
indian_food                       0
italian_food                      0
life_rewarding                    0
marital_status                    0
meals_dinner_friend               2
mother_education                  0
mother_profession                 1
nutritional_check                 0
on_off_campus                     0
parents_cook                      0
pay_meal_out                      0
persian_food                      0
self_perception_weight            0
soup                              0
sports                            0
thai_food                         0
tortilla_calories                 0
turkey_calories                   0
type_sports                      25
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            2
price                           124
dtype: int64

In [63]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drunkeness',
       'stress, boredom, cold weather', 'stres, boredom, and nighttime',
       'Hunger and Boredom ',
       'boredom, sadness, and if it has a good taste. ',
       'boredom, stressed, sad', 'Boredom usually', 'Stress',
       'boredom, stress', 'No reasons ',
       "Usually if I'm sad or depressed. ", 'Tired ', 'Boredom!, sadness',
       'All of the above; sadness, boredom and confusion ',
       'Stress, boredom, craving', 'Hunger, boredom',
       'sadness, boredom, & anger ', 'Boredom, happiness, distraught ',
       'stressed, upset, or just craving a cheat meal',
       'They taste better than other food. They are a pickme up. They are easy to make',
       'Stress, boredom', 'Lazy', 'Boredom, sadness and anger ',
       'Boredom, sadness', 'stress, anger and boredom', 'bored, stress',
       'I usually only eat comfort foods when I am bored. I will also eat them when I am happy to celebrate and then when I am sad to comfort me.',
       'Just cause ', 'Stress, boredom, sadness',
       'Boredom. Celebration. ', 'Sadness, boredom, lonely.',
       'I do not really eat "comfort food" but I guess sadness, special occasions, and anxiety ',
       'boredom, sadness', 'sadness', 'Bordem, happiness, sadness',
       'Stress, sadness, bored ', 'Boredom, stress, and it tastes good',
       'Bad day, bored, sadness',
       'Boredom, being in your period, and long bus rides for softball',
       'boredom, anger, happy', 'Boredom, stress', nan,
       'sadness, stressed, boredom', 'boredom and stress',
       'Boredom comfort hunger ', 'happiness, hunger, sadness',
       'Boredom, sadness, or with friends ',
       'Sadness, Loneliness, Boredom', 'Mostly Stress',
       'boredom, sadness ', 'when i am sad or craving',
       'stress, boredom, college as whole ', 'Boredom and stress',
       'Stress, sadness, boredom', 'laziness and hungover',
       'Boredom, hunger, snacking.', 'Happiness, sadness, celebration.',
       'Boredom, anger and just being hungry in general.',
       'Depression, comfort, accessibility ',
       'they are yummy, my boyfriend sometimes makes me sad, boredom',
       'Sad, bored, excited', 'boredom, stress, mood swings',
       'Anger, sadness',
       'Anxiousness, watching TV I desire "comfort food" ',
       'Boredom, sadness, anxiety', 'Boredom, laziness, anger',
       'Stress and sadness',
       'I am always stressed out, and bored when I am in my apartment. ',
       'Stress, frustration, self-consciousness ', 'Sadness and cravings',
       'Sadness, happiness and boredom', 'Boredom and sadness',
       'sadness, happiness and hunger',
       'Stress, boredom and physical activity',
       'loneliness, homework, boredom ',
       "When i'm  eating with my close friends/ Food smell or look good/ when I feel tired",
       'Happiness, boredom, social event', 'boredom and sadness ',
       'Loneliness / Homesick / Sadness',
       'happiness, they are some of my favorite foods',
       'hormones, Premenstrual syndrome.'], dtype=object)

In [64]:
mean_smfe = df['comfort_food_reasons'].mode() 
df['comfort_food_reasons'] =  df['comfort_food_reasons'].fillna(mean_smfe)

In [65]:
df['eating_changes'].unique()

array(['eat faster ', 'I eat out more than usual. ',
       'sometimes choosing to eat fast food instead of cooking simply for convenience',
       'Accepting cheap and premade/store bought foods',
       'I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ',
       'Eating rice everyday. Eating less homemade food.',
       "I started eating a lot less and healthier because I wasn't playing sports year round anymore.",
       'Freshmen year i ate very unhealthy, but now it is much healthier because of self control.',
       'I snack less',
       "I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe. ",
       'Nun ', 'Less meat. ',
       'I have been eating a lot more salads and soups.',
       'not as healthy because healthy food goes bad quickly and it is expensive',
       'I knew I would eat alot my freshmen year, before coming to college i had a diet plan. ',
       'none', 'More Water ',
       'I would say i just eat a little more, but not in a bad way. I have unlimited swipes at the cafe so instead of snacking on chips before lunch or dinner i will get something from the cafe.',
       'I ate at the food hall.', 'None really', 'Late night food',
       'Less money, less food :(', 'got worse ',
       'Drink coffee all the time. ',
       'I watch the amount of "snacks" I eat more than I did in high school.',
       'none, I have dormed since high school',
       'Tend to eat more fried foods ', 'A lot healthier ',
       'Too much beef jerky',
       'Eating less vegetables because they are less available to me. ',
       'I drink way more coffee and I dont eat at home as often.',
       'I eat more junk food now.', 'I eat more junk food', 'poor',
       'My diet is more limited just because of what I have time to make',
       "I do not snack as often at school. I find that I'm always busy so sometimes I don't have a lot of time to eat. ",
       'I do not eat as many home cooked meals.',
       'I have eaten bigger meals.', 'I eat more ',
       'I eat pretty much the same as I use too. I do have more sweets now though. ',
       'I do not make my own food very much', 'I do not make my own food',
       'Now I prepare my own meals, pack my lunch every day and avoid eating out to save money as much as possible.',
       "I haven't changed much. If anything, I have become more disciplined. ",
       'I eat smaller portions more often',
       'Eating more pizza and burgers or fast food.  ',
       'Cereal became an anytime of day food',
       'Transitioning from home-cooked meals to cafeteria food',
       'I definitely eat less veggies. ',
       'I have started eating a lot healthier.', 'Mediocre ',
       'I eat very bad on the weekends. ', nan,
       'I eat a lot more healthier',
       'when i eat has changed alot. I have to eat at a certain time everyday or the dining hall wont have food.',
       'I have begun to eat more fruits and vegetables because I have been more aware of my physique.',
       'Really paid more attention to what I eat cause it is easy to gain ',
       'More easy meals like pasta.', 'More snacking ',
       "At first I ate less but now that I'm in season playing a sport I eat more.",
       'I have gotten healthier with my eating habits. As a result my parents starting eating healthier too, even though I do not live with them.',
       'As an athlete it is important to fuel my body with important foods only.',
       'I ate more junk food, but also more fruit. ',
       'I snack more, having fewer full meals',
       'I eat more fried food, such as french fries.',
       'I eat a lot less than I did at home but find myself snacking more than actual meals. ',
       "I don't eat as healthy because there aren't as many healthy options at the dinning hall. ",
       'Freshman year I did not watch my diet at all and really let myself go. I ate pizza and fries for almost every meal. Summer following freshman year I knew I needed to stop doing that so I cut out as many refined carbs as I could and try to eat healthier portions.',
       "I don't eat as often",
       'I tend to snack more and have smaller meals.',
       'I eat a lot less and more junk food.',
       'I stopped drinking soda and only drink water now',
       'I do not eat as many fruits and vegetables as I normally would as being home even though i do eat them still',
       'I eat less healthy breakfast now, usually just grab something quick like a granola bar.',
       'Expansion of eating variety ',
       'not going to Egan every meal maybe once a day',
       'More coffee less water ', 'Less fruits and veggies',
       'convenience food ', 'Food is not as healthy. ',
       'Eating at Egan or the laker has definitely made me gain weight because every time I go home and eat I lose weight. ',
       'Huge changes have occurred. I eat far healthier, less processed  food, less dense carbohydrates and way more vegetables and fruits.',
       'I eat way too often and way too much x', 'Less snacking ',
       'less healthy because of less options, money and time.',
       'Willingly eating vegetables ',
       'I have been eating healthier especially vegetables and proteinous food ',
       'i eat healthier all around',
       "Home cooked meals and a lot more difficult to have at college. It's typically quick, on the go foods. ",
       'I have increased the amounts of vegetables I eat due to the unhealthy options in our dining halls',
       'I eat alot of carbs and eat much more frequently',
       'I eat whatever is offered at egan or at the laker',
       "Food is readily available so I don't have to cook so it's easier to eat a lot.",
       "I've eaten more fruits and vegetables. Started eating seafood.",
       'Coming to college I definitely have tried to change my eating habits in order to maintain my weight and be more healthy. ',
       'When I was on campus (which I am not anymore) I ate way more fruits and vegetables since I had easy access to them.',
       'eat more salads',
       "I consume a lot more grapefuit since I've come to college. The meals here are also more greasy than I am used to. ",
       'I eat a lot more carbs than I did when I lived at home.',
       'Avoiding "easy options" such as junk foods ',
       'Coming to college I have ate less well colored meals each day due to lack of income and desire to save money. I used to eat more fruits and vegetables, more chicken and salmon, now these habits have lightened up and are not as frequent and regular in the week. I have also started eating more bread and dairy products.',
       "I've definitely gotten used to eating more often since I have a fully cooked meal available to me at all the time.  Sometimes I would only eat one full meal and a snack in high school because I was so busy and did not have the time to cook. ",
       'I do not eat full meals. Rarely eat 3 meals a day. ',
       "I have been drinking more water. Since college, I've been more conscious about my diet and incorporated more fruits on my diet. ",
       'My diet could improve now. I have been eating more than I should.',
       'Late night snacking', 'I snack less and eat smaller portions ',
       'I eat out more. ',
       'I had to change a lot. I keep track of calories and cut out most breads and wraps.',
       'They have gotten very bad. I eat a lot more food that I know I should not eat. ',
       'not eating meals on time',
       'Eating more dairy due to more ice cream intake.',
       'less vegetable more sweats',
       'I eat more vegetable. Since coming to college, I started to eat salads and tried to eat salads at least three times a week.',
       'I try to eat more fruits and vegetables ',
       'Started eating a lot of protein rich food that i didnt before.',
       'I have noticed there is less time for a prepared meal, so quick and easy has become the norm.',
       'Eating Pizza as an excuse when there is nothing else to it.',
       'less rice',
       "I don't eat as much on a daily basis since coming to college.",
       'I have learned to eat more vegetables. '], dtype=object)

In [66]:
mean_smfe = df['eating_changes'].mode() 
df['eating_changes'] =  df['eating_changes'].fillna(mean_smfe)

In [67]:
df['eating_changes'].unique()

array(['eat faster ', 'I eat out more than usual. ',
       'sometimes choosing to eat fast food instead of cooking simply for convenience',
       'Accepting cheap and premade/store bought foods',
       'I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ',
       'Eating rice everyday. Eating less homemade food.',
       "I started eating a lot less and healthier because I wasn't playing sports year round anymore.",
       'Freshmen year i ate very unhealthy, but now it is much healthier because of self control.',
       'I snack less',
       "I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe. ",
       'Nun ', 'Less meat. ',
       'I have been eating a lot more salads and soups.',
       'not as healthy because healthy food goes bad quickly and it is expensive',
       'I knew I would eat alot my freshmen year, before coming to college i had a diet plan. ',
       'none', 'More Water ',
       'I would say i just eat a little more, but not in a bad way. I have unlimited swipes at the cafe so instead of snacking on chips before lunch or dinner i will get something from the cafe.',
       'I ate at the food hall.', 'None really', 'Late night food',
       'Less money, less food :(', 'got worse ',
       'Drink coffee all the time. ',
       'I watch the amount of "snacks" I eat more than I did in high school.',
       'none, I have dormed since high school',
       'Tend to eat more fried foods ', 'A lot healthier ',
       'Too much beef jerky',
       'Eating less vegetables because they are less available to me. ',
       'I drink way more coffee and I dont eat at home as often.',
       'I eat more junk food now.', 'I eat more junk food', 'poor',
       'My diet is more limited just because of what I have time to make',
       "I do not snack as often at school. I find that I'm always busy so sometimes I don't have a lot of time to eat. ",
       'I do not eat as many home cooked meals.',
       'I have eaten bigger meals.', 'I eat more ',
       'I eat pretty much the same as I use too. I do have more sweets now though. ',
       'I do not make my own food very much', 'I do not make my own food',
       'Now I prepare my own meals, pack my lunch every day and avoid eating out to save money as much as possible.',
       "I haven't changed much. If anything, I have become more disciplined. ",
       'I eat smaller portions more often',
       'Eating more pizza and burgers or fast food.  ',
       'Cereal became an anytime of day food',
       'Transitioning from home-cooked meals to cafeteria food',
       'I definitely eat less veggies. ',
       'I have started eating a lot healthier.', 'Mediocre ',
       'I eat very bad on the weekends. ', nan,
       'I eat a lot more healthier',
       'when i eat has changed alot. I have to eat at a certain time everyday or the dining hall wont have food.',
       'I have begun to eat more fruits and vegetables because I have been more aware of my physique.',
       'Really paid more attention to what I eat cause it is easy to gain ',
       'More easy meals like pasta.', 'More snacking ',
       "At first I ate less but now that I'm in season playing a sport I eat more.",
       'I have gotten healthier with my eating habits. As a result my parents starting eating healthier too, even though I do not live with them.',
       'As an athlete it is important to fuel my body with important foods only.',
       'I ate more junk food, but also more fruit. ',
       'I snack more, having fewer full meals',
       'I eat more fried food, such as french fries.',
       'I eat a lot less than I did at home but find myself snacking more than actual meals. ',
       "I don't eat as healthy because there aren't as many healthy options at the dinning hall. ",
       'Freshman year I did not watch my diet at all and really let myself go. I ate pizza and fries for almost every meal. Summer following freshman year I knew I needed to stop doing that so I cut out as many refined carbs as I could and try to eat healthier portions.',
       "I don't eat as often",
       'I tend to snack more and have smaller meals.',
       'I eat a lot less and more junk food.',
       'I stopped drinking soda and only drink water now',
       'I do not eat as many fruits and vegetables as I normally would as being home even though i do eat them still',
       'I eat less healthy breakfast now, usually just grab something quick like a granola bar.',
       'Expansion of eating variety ',
       'not going to Egan every meal maybe once a day',
       'More coffee less water ', 'Less fruits and veggies',
       'convenience food ', 'Food is not as healthy. ',
       'Eating at Egan or the laker has definitely made me gain weight because every time I go home and eat I lose weight. ',
       'Huge changes have occurred. I eat far healthier, less processed  food, less dense carbohydrates and way more vegetables and fruits.',
       'I eat way too often and way too much x', 'Less snacking ',
       'less healthy because of less options, money and time.',
       'Willingly eating vegetables ',
       'I have been eating healthier especially vegetables and proteinous food ',
       'i eat healthier all around',
       "Home cooked meals and a lot more difficult to have at college. It's typically quick, on the go foods. ",
       'I have increased the amounts of vegetables I eat due to the unhealthy options in our dining halls',
       'I eat alot of carbs and eat much more frequently',
       'I eat whatever is offered at egan or at the laker',
       "Food is readily available so I don't have to cook so it's easier to eat a lot.",
       "I've eaten more fruits and vegetables. Started eating seafood.",
       'Coming to college I definitely have tried to change my eating habits in order to maintain my weight and be more healthy. ',
       'When I was on campus (which I am not anymore) I ate way more fruits and vegetables since I had easy access to them.',
       'eat more salads',
       "I consume a lot more grapefuit since I've come to college. The meals here are also more greasy than I am used to. ",
       'I eat a lot more carbs than I did when I lived at home.',
       'Avoiding "easy options" such as junk foods ',
       'Coming to college I have ate less well colored meals each day due to lack of income and desire to save money. I used to eat more fruits and vegetables, more chicken and salmon, now these habits have lightened up and are not as frequent and regular in the week. I have also started eating more bread and dairy products.',
       "I've definitely gotten used to eating more often since I have a fully cooked meal available to me at all the time.  Sometimes I would only eat one full meal and a snack in high school because I was so busy and did not have the time to cook. ",
       'I do not eat full meals. Rarely eat 3 meals a day. ',
       "I have been drinking more water. Since college, I've been more conscious about my diet and incorporated more fruits on my diet. ",
       'My diet could improve now. I have been eating more than I should.',
       'Late night snacking', 'I snack less and eat smaller portions ',
       'I eat out more. ',
       'I had to change a lot. I keep track of calories and cut out most breads and wraps.',
       'They have gotten very bad. I eat a lot more food that I know I should not eat. ',
       'not eating meals on time',
       'Eating more dairy due to more ice cream intake.',
       'less vegetable more sweats',
       'I eat more vegetable. Since coming to college, I started to eat salads and tried to eat salads at least three times a week.',
       'I try to eat more fruits and vegetables ',
       'Started eating a lot of protein rich food that i didnt before.',
       'I have noticed there is less time for a prepared meal, so quick and easy has become the norm.',
       'Eating Pizza as an excuse when there is nothing else to it.',
       'less rice',
       "I don't eat as much on a daily basis since coming to college.",
       'I have learned to eat more vegetables. '], dtype=object)

In [68]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     2
diet_current             0
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             0
ideal_diet               0
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [69]:
df['comfort_food_reasons'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88      True
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: comfort_food_reasons, dtype: bool

In [70]:
mode_value = df["comfort_food_reasons"].mode()[0]

df.loc[[74, 88], "comfort_food_reasons"] = mode_value

In [71]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     0
diet_current             0
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             0
ideal_diet               0
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [72]:
df['eating_changes'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53      True
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63      True
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: eating_changes, dtype: bool

In [73]:
mode_value = df["eating_changes"].mode()[0]

df.loc[[74, 53, 63], "eating_changes"] = mode_value

In [74]:
df['father_profession'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30      True
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97      True
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: father_profession, dtype: bool

In [76]:
df['fav_cuisine'].isnull().sum()

np.int64(1)

In [78]:
df['food_childhood'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: food_childhood, dtype: bool

In [80]:
df['meals_dinner_friend'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101     True
102     True
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: meals_dinner_friend, dtype: bool

In [81]:
mode_value = df["meals_dinner_friend"].mode()[0]

df.loc[[101], "meals_dinner_friend"] = mode_value

In [82]:
df['mother_profession'].isnull().sum()

np.int64(1)

In [83]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     0
diet_current             0
eating_changes           0
father_profession        2
fav_cuisine              1
food_childhood           0
healthy_meal             0
ideal_diet               0
meals_dinner_friend      1
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [ ]:
df['type_sports'].isnull()

In [84]:
mode_typ_sp= df['type_sports'].mode() 
df['type_sports'] =  df['type_sports'].fillna(mode_typ_sp)

In [85]:
null_locs = df[df['type_sports'].isnull()].index
print(null_locs)

Index([  3,  16,  28,  29,  33,  41,  42,  50,  53,  61,  65,  69,  72,  74,
        80,  88,  93, 101, 102, 106, 112, 113, 118, 123, 124],
      dtype='int64')

In [86]:
mode_value = df["type_sports"].mode()[0]

df.loc[[  3,  16,  28,  29,  33,  41,  42,  50,  53,  61,  65,  69,  72,  80,
        88,  93, 101, 102, 106, 112, 113, 118, 123, 124], "type_sports"] = mode_value

In [87]:
df[ob_columns].isnull().sum()

comfort_food            0
comfort_food_reasons    0
diet_current            0
eating_changes          0
father_profession       2
fav_cuisine             1
food_childhood          0
healthy_meal            0
ideal_diet              0
meals_dinner_friend     1
mother_profession       1
type_sports             1
weight                  2
dtype: int64

In [88]:
df['meals_dinner_friend'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102     True
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: meals_dinner_friend, dtype: bool

In [89]:
mode_value = df["meals_dinner_friend"].mode()[0]

df.loc[[102], "meals_dinner_friend"] = mode_value

In [90]:
df['weight'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32      True
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
Name: weight, dtype: bool

In [91]:
mode_value = df["weight"].mode()[0]

df.loc[[32], "weight"] = mode_value

In [92]:
df[ob_columns].isnull().sum()

comfort_food            0
comfort_food_reasons    0
diet_current            0
eating_changes          0
father_profession       2
fav_cuisine             1
food_childhood          0
healthy_meal            0
ideal_diet              0
meals_dinner_friend     0
mother_profession       1
type_sports             1
weight                  1
dtype: int64

In [93]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              0
comfort_food_reasons_coded        0
cook                              0
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      0
diet_current_coded                0
drink                             0
eating_changes                    0
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        0
ethnic_food                       0
exercise                          0
father_education                  0
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                          0
food_childhood                    0
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      0
ideal_diet                        0
ideal_diet_coded                  0
income                            0
indian_food                       0
italian_food                      0
life_rewarding                    0
marital_status                    0
meals_dinner_friend               0
mother_education                  0
mother_profession                 1
nutritional_check                 0
on_off_campus                     0
parents_cook                      0
pay_meal_out                      0
persian_food                      0
self_perception_weight            0
soup                              0
sports                            0
thai_food                         0
tortilla_calories                 0
turkey_calories                   0
type_sports                       1
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            1
price                           124
dtype: int64

In [94]:
df.head(25)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400000,2,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,1.000000,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654000,1,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.000000,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300000,1,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,2.000000,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200000,1,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,2.000000,5,725.0,690,none,3,1,1315,"Not sure, 240",NaN
4,3.500000,1,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.000000,4,940.0,500,Softball,4,2,760,190,NaN
5,2.250000,1,1,610,3.000000,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,2.000000,4,940.0,345,None.,1,2,1315,190,NaN
6,3.800000,2,1,610,3.000000,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.000000,5,940.0,690,soccer,4,1,1315,180,NaN
7,3.300000,1,1,720,3.000000,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,2.000000,1,725.0,500,none,4,2,1315,137,NaN
8,3.300000,1,1,430,3.038095,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.000000,5,725.0,345,none,3,2,760,180,NaN
9,3.300000,1,1,430,3.000000,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.000000,4,580.0,345,field hockey,5,1,900,125,NaN
10,3.500000,1,1,610,3.000000,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.000000,2,940.0,345,soccer,5,2,900,116,NaN
11,3.904000,1,1,720,4.000000,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.000000,5,940.0,500,Running,5,1,900,110,NaN
12,3.400000,2,1,430,3.000000,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,1.000000,3,940.0,500,Soccer and basketball,3,2,575,264,NaN
13,3.600000,1,1,610,3.000000,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.000000,5,1165.0,850,intramural volleyball,5,2,1315,123,NaN
14,3.100000,2,1,610,3.000000,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.000000,4,940.0,500,Hockey,5,1,900,185,NaN
15,3.419891,2,2,430,3.038095,980.0,2,"cookies, donuts, candy bars",boredom,2.0,...,1.000000,1,940.0,345,Hockey,1,2,1315,180,NaN
16,4.000000,1,1,265,3.000000,420.0,1,"Saltfish, Candy and Kit Kat",Stress,1.0,...,2.000000,1,580.0,345,none,5,1,760,145,NaN
17,3.600000,2,1,430,3.000000,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.000000,3,940.0,500,hockey,4,2,900,170,NaN
18,3.400000,1,1,720,3.000000,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.000000,1,1165.0,690,dancing,5,1,1315,135,NaN
19,2.200000,2,1,430,2.000000,420.0,2,"pizza, wings, Chinese","boredom, sadness, hungry",2.0,...,1.385246,3,940.0,345,basketball,2,2,900,165,NaN
20,3.300000,2,1,610,3.000000,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.000000,1,1165.0,850,Soccer,3,2,1315,175,NaN
21,3.870000,2,1,610,3.000000,315.0,1,"chocolate, sweets, ice cream",Mostly boredom,2.0,...,1.000000,5,725.0,500,Tennis,2,2,900,195,NaN
22,3.700000,2,1,610,3.000000,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.000000,4,940.0,850,tennis soccer gym,3,1,1315,185,NaN
23,3.700000,2,2,610,3.000000,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.000000,4,940.0,690,Gaelic Football,4,1,1315,185,NaN
24,3.900000,1,1,720,2.000000,420.0,2,"Soup, pasta, brownies, cake","A long day, not feeling well, winter",6.0,...,2.000000,4,940.0,500,none,4,2,1315,105,NaN

In [95]:
df['Gender'] = df['Gender'].replace({2: 'female', 1: 'male'})

In [96]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400,female,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,1.0,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654,male,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300,male,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200,male,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,2.0,5,725.0,690,none,3,1,1315,"Not sure, 240",NaN
4,3.500,male,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,4,940.0,500,Softball,4,2,760,190,NaN

In [101]:
df['sports'] = df['sports'].replace({'Yes': 'Active', 'No': 'Not-Active'})

In [102]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400,female,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,Active,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654,male,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,Active,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300,male,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,Not-Active,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200,male,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,Not-Active,5,725.0,690,none,3,1,1315,"Not sure, 240",NaN
4,3.500,male,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,Active,4,940.0,500,Softball,4,2,760,190,NaN

### Using replace(): the numerical data type column

In [103]:
df['breakfast'] = df['breakfast'].astype(str).replace({'1' : 'Yes', '2' : 'No'})

In [104]:
df['coffee'] = df['coffee'].astype(str).replace({'1' : 'Yes', '2' : 'No'})

AttributeError: 'DataFrame' object has no attribute 'col'