In [35]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:\YIU\YIU\LevelFive\BPS\laptopData.xls")

In [36]:
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [37]:
df.shape

(1303, 12)

In [38]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [39]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

### Missing Values Handle

In [40]:
df.isnull().sum()

Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [41]:
df.dtypes

Company              object
TypeName             object
Inches               object
ScreenResolution     object
Cpu                  object
Ram                  object
Memory               object
Gpu                  object
OpSys                object
Weight               object
Price               float64
dtype: object

## Drop all Absent rows

In [42]:
df = df.dropna(how='all')

In [43]:
df.isnull().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

## Drop Duplicat Rows

In [44]:
df.duplicated().sum()

np.int64(29)

In [45]:
df = df.drop_duplicates(keep= 'first')

In [46]:
df.duplicated().sum()

np.int64(0)

## Find Missing values(?, '', unknown)

In [47]:
df['Company'].value_counts()

Company
Lenovo       282
Dell         281
HP           260
Asus         149
Acer         101
MSI           53
Toshiba       47
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
LG             3
Huawei         2
Fujitsu        2
Name: count, dtype: int64

In [48]:
df['TypeName'].value_counts()

TypeName
Notebook              689
Gaming                203
Ultrabook             189
2 in 1 Convertible    112
Workstation            29
Netbook                22
Name: count, dtype: int64

In [49]:
df['Inches'].value_counts()

Inches
15.6    621
14      188
17.3    162
13.3    157
12.5     38
11.6     29
12        6
13.9      6
13.5      5
12.3      5
15.4      4
15        4
35.6      3
10.1      3
24        2
13        2
18.4      1
27.3      1
33.5      1
?         1
31.6      1
17        1
14.1      1
11.3      1
25.6      1
Name: count, dtype: int64

In [50]:
df['Inches'].unique()

array(['13.3', '15.6', '15.4', '14', '12', '17.3', '13.5', '12.5', '13',
       '18.4', '13.9', '11.6', '25.6', '35.6', '12.3', '27.3', '24',
       '33.5', '?', '31.6', '17', '15', '14.1', '11.3', '10.1'],
      dtype=object)

In [51]:
df[df['Inches'].isnull()].index

Index([], dtype='int64')

In [52]:
df[df['Inches']=='?'].index.tolist()

[476]

In [53]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [54]:
df['Inches'].replace('?', np.nan)

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1269    15.6
1270      14
1271    13.3
1272      14
1273    15.6
Name: Inches, Length: 1244, dtype: object

In [55]:
df[df['Inches']=='?'].index.tolist()

[476]

In [56]:
df.loc[476]

Company                                    Dell
TypeName                            Workstation
Inches                                        ?
ScreenResolution              Full HD 1920x1080
Cpu                 Intel Core i7 7700HQ 2.8GHz
Ram                                         8GB
Memory                                256GB SSD
Gpu                         Nvidia Quadro M1200
OpSys                                Windows 10
Weight                                   1.78kg
Price                                 128298.24
Name: 476, dtype: object

In [68]:
df['Inches'] = df['Inches'].astype(float)

In [69]:
df['Inches'] = df['Inches'].replace(['?', 'unknown', ''], np.nan)

In [70]:
df.loc[476]

Company                                    Dell
TypeName                            Workstation
Inches                                      NaN
ScreenResolution              Full HD 1920x1080
Cpu                 Intel Core i7 7700HQ 2.8GHz
Ram                                         8GB
Memory                                256GB SSD
Gpu                         Nvidia Quadro M1200
OpSys                                Windows 10
Weight                                   1.78kg
Price                                 128298.24
Name: 476, dtype: object

In [71]:
df['Inches'].replace('?', np.nan)

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1269    15.6
1270    14.0
1271    13.3
1272    14.0
1273    15.6
Name: Inches, Length: 1244, dtype: float64

In [72]:
df.loc[476]

Company                                    Dell
TypeName                            Workstation
Inches                                      NaN
ScreenResolution              Full HD 1920x1080
Cpu                 Intel Core i7 7700HQ 2.8GHz
Ram                                         8GB
Memory                                256GB SSD
Gpu                         Nvidia Quadro M1200
OpSys                                Windows 10
Weight                                   1.78kg
Price                                 128298.24
Name: 476, dtype: object

In [73]:
df.dtypes

Company              object
TypeName             object
Inches              float64
ScreenResolution     object
Cpu                  object
Ram                  object
Memory               object
Gpu                  object
OpSys                object
Weight               object
Price               float64
dtype: object

In [74]:
df['Inches']= df['Inches'].fillna(df['Inches'].mean())

In [75]:
df.loc[476]

Company                                    Dell
TypeName                            Workstation
Inches                                15.138858
ScreenResolution              Full HD 1920x1080
Cpu                 Intel Core i7 7700HQ 2.8GHz
Ram                                         8GB
Memory                                256GB SSD
Gpu                         Nvidia Quadro M1200
OpSys                                Windows 10
Weight                                   1.78kg
Price                                 128298.24
Name: 476, dtype: object

In [76]:
df.head()

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [79]:
df['Memory'].value_counts()

Memory
256GB SSD                        401
1TB HDD                          209
500GB HDD                        121
512GB SSD                        112
128GB SSD +  1TB HDD              92
128GB SSD                         72
256GB SSD +  1TB HDD              71
32GB Flash Storage                35
2TB HDD                           16
512GB SSD +  1TB HDD              14
1TB SSD                           13
64GB Flash Storage                12
256GB SSD +  2TB HDD              10
256GB Flash Storage                8
16GB Flash Storage                 7
1.0TB Hybrid                       7
32GB SSD                           6
180GB SSD                          4
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
128GB SSD +  2TB HDD               2
256GB SSD +  500GB HDD             2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
?                                  1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [80]:
df[df['Memory']=='?'].index.tolist()

[770]

In [85]:
common_Memory = df['Memory'].value_counts().idxmax()

In [87]:
df['Memory'] = df['Memory'].replace('?', common_Memory)

In [89]:
df['Memory'].loc[770]

'256GB SSD'

# Find mode
memory_mode = df['Memory'].mode() 
df['Memory'] =  df['Memory'].fillna(memory_mode)[0]

## How to sloce Validity Issues

In [91]:
# this values might be 2kg
df.loc[df['Weight'] == '0.0002kg', 'Weight'] = '2.0kg'

In [92]:
df.loc[df['Weight'] == '8.4kg', 'Weight'] = '1.27kg'

## Accuracy Issues

In [95]:
## 64GB to 8GB
df.loc[[68, 702], 'Ram'] = '8GB'

In [97]:
df.loc[df['Ram'] == '1GB', 'Ram'] = '8GB'

In [99]:
df['TypeName'].unique()

array(['Ultrabook', 'Notebook', 'Gaming', '2 in 1 Convertible',
       'Workstation', 'Netbook'], dtype=object)

In [100]:
df['TypeName'].value_counts()

TypeName
Notebook              689
Gaming                203
Ultrabook             189
2 in 1 Convertible    112
Workstation            29
Netbook                22
Name: count, dtype: int64

In [101]:
df[df['TypeName']=='Netbook'].index.tolist()

[376,
 430,
 461,
 500,
 504,
 515,
 584,
 695,
 750,
 804,
 805,
 817,
 828,
 888,
 906,
 935,
 990,
 1049,
 1094,
 1215,
 1230,
 1268]

In [102]:
df.loc[df['TypeName'] == 'Netbook', 'TypeName'] = 'Notebook'

In [103]:
df['TypeName'].unique()

array(['Ultrabook', 'Notebook', 'Gaming', '2 in 1 Convertible',
       'Workstation'], dtype=object)

In [ ]:
df.to_csv(D:\YIU\YIU\LevelFive\BPS")